name: i2p
services:
  server:
    image: 'geti2p/i2p:latest'
    container_name: i2pd
    hostname: ${BASE_HOST_NAME:-i2p}
    restart: always
    pull_policy: always
    environment:
      - JVM_XMX=1024m
      - EXT_PORT=54321
      - IP_ADDR=0.0.0.0
    ports:
      - '4444:4444'
      - '4445:4445'
      - '6668:6668'
      - '7654:7654'
      - '7656:7656'
      - '7658:7658'
      - '7659:7659'
      - '7660:7660'
      - '7652:7652'
      - '7653:7653'
      - '54321:12345'
      - '54321:12345/udp'
      - '172.17.0.1:7657:7657'
    volumes:
      - 'i2pd:/i2p/.i2p'
      - '${HOME}/Downloads/snark:/i2psnark'
    networks:
      - i2p

volumes:
  i2pd:
  snark:

networks:
  i2p:
    name: i2p
    external: false
